### PR TITLE
DP-23508 Remove CloudFlare module as we use Akamai

### PR DESCRIPTION
**Pull request by deviantintegral**
**Description:**
Cleaning up a module that is no longer installed on the site.

**Jira:** (Skip unless you are MA staff)
DP-23508

**To Test:**
- [ ] Static tests passing

---

[Peer Review Checklist](https://github.com/massgov/openmass/blob/develop/docs/peer_review_checklist.md)

### CODE REVIEW

**Comment by weitzman** [comment]
This looks good. It has merge conflicts but thats the bane of our existence. Not sure when will be a good time to reroll this. There are other PRs like entity usage that are rerolling too.

**Comment by deviantintegral** [comment]
I am happy to resolve conflicts and turn on auto-merge after pushing. Eventually it will get in!

**Comment by deviantintegral** [comment]
Just heard the entity usage PR is ready to merge, so given that's real features I'll do this one after.

**Comment by weitzman** [comment]
I put this into #1450 so we dont get even more merge conflicts. Thats merged so closing this one.

**Pull request closed without merging**
