### PR TITLE
Dp 23717 add image to collection page results

### PR DESCRIPTION
**Pull request by beto-aveiga**
**Description:**
Explain the technical implementation of the work done.

**Jira:** (Skip unless you are MA staff)
DP-****

**To Test:**
- [ ] Add steps to test this feature

---

[Peer Review Checklist](https://github.com/massgov/openmass/blob/develop/docs/peer_review_checklist.md)

### CODE REVIEW

**Comment by clairesunstudio** [comment]
Screen Shot 2022-01-19 at 4 42 46 PM

To do:
I don't see the field for the image alt text in content of openmass/docroot/themes/custom/mass_theme/templates/content/node--news--listing.html.twig
- [ ] Please expose that and pass it into `generalTeaser.image.alt`
- [ ] Add a changelog

**Comment by clairesunstudio** [comment]
link to MF https://github.com/massgov/mayflower/pull/1586

**Comment by clairesunstudio** [comment]
Mobile:
Screen Shot 2022-01-27 at 5 04 11 PM

Desktop:
Screen Shot 2022-01-27 at 5 03 30 PM

**Review by ygannett — COMMENTED** [review]
Since the imaged link is a duplicated link to the linked title, I recommend to remove a link from the image.  Otherwise screen reader users need to go through the same links as an extra item.  That is not convenient to them.

In the [Mayflower PR](https://github.com/massgov/mayflower/pull/1586), it seems that it doesn't link the image when its href value is null.

Also, in this particular case, the image itself is not providing necessary information to screen reader users considering the purpose of the component is to provide information for the linked page.  The image is considered decorative.  I recommend to keep the `alt` empty.
```
<section class="ma__general-teaser ma__general-teaser--image stacked">
  <a class="ma__general-teaser__image-wrapper" 
     href="/news/aaa-governor-baker-urges-all-residents-to-avoid-travel-throughout-winter-storm" 
     title="AAA - Governor Baker Urges All Residents to Avoid Travel Throughout Winter Storm">
    <img class="ma__image" alt="Alt text for this image" src="/sites/default/files/styles/565x/public/2022-01/green-nature-1600x400.jpg?itok=DKpb62e_" width="400">
  </a>

  <div class="ma__general-teaser__details">
    <div class="ma__general-teaser__eyebrow"><span>Press Release</span></div>

    <h2 class="ma__general-teaser__title">
      <span class="ma__decorative-link">
        <a href="/news/aaa-governor-baker-urges-all-residents-to-avoid-travel-throughout-winter-storm" class="js-clickable-link">
          AAA - Governor Baker Urges All Residents to Avoid Travel Throughout Winter Storm&nbsp;<svg aria-hidden="true" focusable="false"><use xlink:href="#2941c74825ac6b2aab1eeb97bfe8461a"></use></svg>
        </a>
      </span>
    </h2>

    <div class="ma__general-teaser__emph-text-wrapper">
      <span class="ma__general-teaser__emph-text">1/28/2022</span>
      <span class="ma__general-teaser__emph-text">Office of Governor Charlie Baker and Lt. Governor Karyn Polito</span>
    </div>
    <div class="ma__general-teaser__contents">
      <p></p>              
    </div>
  </div><!-- ma__general-teaser__details -->
</section>
```
With the recommended change, the markup looks:
```
<section class="ma__general-teaser ma__general-teaser--image stacked">
    <span class="ma__general-teaser__image-wrapper">
        <img class="ma__image" alt="" src="/sites/default/files/styles/565x/public/2022-01/green-nature-1600x400.jpg?itok=DKpb62e_" width="400">
     </span>

  <div class="ma__general-teaser__details">
    <div class="ma__general-teaser__eyebrow"><span>Press Release</span></div>

    <h2 class="ma__general-teaser__title">
      <span class="ma__decorative-link">
        <a href="/news/aaa-governor-baker-urges-all-residents-to-avoid-travel-throughout-winter-storm" class="js-clickable-link">
          AAA - Governor Baker Urges All Residents to Avoid Travel Throughout Winter Storm&nbsp;<svg aria-hidden="true" focusable="false"><use xlink:href="#2941c74825ac6b2aab1eeb97bfe8461a"></use></svg>
        </a>
      </span>
    </h2>
    ...
  </div><!-- ma__general-teaser__details -->
</section>
```

**Review by ygannett — COMMENTED** [review]
@beto-aveiga Don't forget to add a changelog!

**Comment by beto-aveiga** [comment]
@clairesunstudio based on @ygannett comment, I removed the link from the image, but that also removed the link to the news.
I think we still need to work in Mayflower to find a way to remove the link from the image, without removing the link to the news.
What do you think?

**Comment by clairesunstudio** [comment]
linking to MF PR https://github.com/massgov/mayflower/pull/1591

**Review by ygannett — COMMENTED** [review]
Confirmed that a link has been removed from the image.  Looks good.  Thank you so much for the work.
Collection___Mass_gov

**Pull request merged**
