### PR TITLE
DP-19675 Add Linked content to text areas.

### PR DESCRIPTION
**Pull request by vordude**
**Description:**
This is the initial framework for adding WYSIWG (textarea) support to the "Pages Linking Here" functionality.

This currently works with all of the WYSIWYG fields that I pulled out of every content type and related paragraph.  It is configured by adding those fields to the node.type.{content_type}.yml file. in the mass_content_api linking_pages section.

**Jira:**
https://jira.mass.gov/browse/DP-19675

**To Test:**
- [ ] View this tab: /news/baker-polito-administration-announces-covid-19-vaccine-advisory-group/linking-page
- [ ] Browse here and click save: http://mass.local/info-details/covid-19-vaccine-frequently-asked-questions/edit
- [ ] Trigger a cron run to insure the queues get run.
- [ ] Repeat step 1.

_If you completely run the mass_content_api_descendant_queue first, you will not see a difference. when running the steps above, since the queue run already queued up the FAQ node for re-indexing of descendant content._ 

- [ ] Find a node that you'd like to link to.
- [ ] Copy and paste the local relative URL (e.g. "/info-details/covid-19-vaccinations-for-health-care-workers")
- [ ] Browse to another unrelated page (e.g. "/how-to/create-your-masstaxconnect-individual-account")
- [ ] Edit the node, and in a WYSIWYG Field, link some text to the first page.
- [ ] Trigger a cron run to insure the queues get run.
- [ ] View the linked pages from the node you edited, and see the first page listed there.

**Screenshots/GIFs:**

Other content is also showing the basic functionality as well.
image

---

[Peer Review Checklist](https://github.com/massgov/openmass/blob/develop/docs/peer_review_checklist.md)

### CODE REVIEW

**Comment by vordude** [comment]
To trigger the queue without waiting for cron:

**drush queue:run mass_content_api_descendant_queue**

This runs everything at once.


Also there are other options that can be used:
Run only 500 Items
**drush queue:run mass_content_api_descendant_queue --items-limit=500**
Run only for 30 seconds
**drush queue:run mass_content_api_descendant_queue -- --time-limit=30**

**Comment by vordude** [comment]
@weitzman The time the queue will run during a cron run appears to be set in the QueueWorker plugin's annotation. DescendantQueueWorker.php says 2 minutes.

image

**Comment by weekbeforenext** [comment]
The code looks sound and functions. Great work!

The following lists were generated by searching for "field_type: text_long" and "field_type: text_with_summary" in the configuration directory. If it's okay to skip these fields then this is all good. Just wanted to make sure we weren't missing any possible locations for links.

There a content types with body (text_with_summary) fields that do not have third-party settings for linking_pages:
* legacy_redirects
* page
* person

There are media type fields with text_long format that aren't listed in any of the node configuration third-party settings for linking_pages:
* field_data_dictionary
* field_video_description

There are paragraph type fields with text_long format that aren't listed in any of the node configuration third-party settings for linking_pages:
* 3_up_text: field_content
* action_step: field_content
* action_step_numbered: field_content
* card: field_content
* custom_html: field_campaign_custom_html
* decision_section: field_decision_section_body
* event_minutes_section: field_event_minutes_body
* external_organization: field_external_org_description
* featured_content_2up_item: field_rich_text_description
* featured_content_single_item: field_rich_text_description
* featured_message: field_featured_message_content
* guide_section: field_guide_section_body
* guide_section_3up: field_guide_section_body_first
* guide_section_3up: field_guide_section_body_second
* guide_section_3up: field_guide_section_body_third
* key_message: field_rich_text_description
* key_message_section: field_rich_text_description
* more_info: field_more_info_text
* next_step: field_next_step_details
* regulation_section: field_regulation_section_body
* section: field_section_body
* section_with_heading: field_section_body
* tableau_embed: field_tabl_caption
* video_with_header: field_campaign_description
* video_with_section: field_campaign_description

**Comment by vordude** [comment]
I'm in favor of spinning off the media fields an paragraph fields off into their own ticket.  I would do that but don't see the link.

**Comment by vordude** [comment]
Added a bunch of new options to fill in April's list above.. 

```

media_download_link
Added a media_download_link linking_page.


field_video_description
Added a field_video_description on linking_page for media_video bundle

3_up_text: field_content  
on stacked_layout>field_bands


action_step: field_content
stacked_layout (x2) and action node type


action_step_numbered: field_content
previously added stacked_layout bands->main->content x2
Already added by       - 'field_bands>field_main>field_action_step_numbered_items>*'


card: field_content
info_details
      - field_info_details_sections>field_section_long_form_content>field_card>field_content

      
custom_html: field_campaign_custom_html
campaign_landing
      - field_header>field_campaign_custom_html
      - field_sections>field_campaign_custom_html

      
decision_section: field_decision_section_body
decision
      - field_decision_section>field_decision_section_body


event_minutes_section: field_event_minutes_body
event 
      - field_event_meeting_minutes>field_event_minutes_body

      
      
external_organization: field_external_org_description
      - field_news_signees>field_external_org_description

      
featured_content_2up_item: field_rich_text_description
campaign_landing
      - field_sections>field_2up_featured_item>field_rich_text_description
      - field_sections>field_2up_featured_item_2>field_rich_text_description
      

featured_content_single_item: field_rich_text_description
campaign_landing
      - field_sections>field_full_width_featured_item>field_rich_text_description


featured_message: field_featured_message_content
org_page
      - field_org_featured_message>field_featured_message_content

guide_section: field_guide_section_body
guide_section_3up: field_guide_section_body_first
guide_section_3up: field_guide_section_body_second
guide_section_3up: field_guide_section_body_third
guide_page
      - field_guide_page_sections>*



key_message: field_rich_text_description
key_message_section: field_rich_text_description
campaign_landing
      - field_header>field_rich_text_description
      - field_sections>field_rich_text_description

      
      
regulation_section: field_regulation_section_body
regulation
      - field_regulation_section>field_regulation_section_body



more_info: field_more_info_text
decision_tree_branch
      - field_more_info>field_more_info_text

    
next_step: field_next_step_details
how_to_page
      - field_how_to_next_steps>field_next_step_details


section: field_section_body
service_details
      - field_service_detail_sections>field_section_body
location_details
      - field_location_details_sections>field_section_body

      
      
section_with_heading: field_section_body
news
      - field_news_sections>field_section_body

      
tableau_embed: field_tabl_caption
info_details 
      -field_info_details_sections>field_section_long_form_content>field_tabl_caption

      
video_with_header: field_campaign_description
campaign_landing
      - field_header>field_campaign_description

      
video_with_section: field_campaign_description
campaign_landing
      - field_sections>field_campaign_description



  mass_content_api:
    parents: null
    children: null
    linking_pages:
      - body
```

**Pull request merged**
