### PR TITLE
Dp 25168 instrument cache hit rate for metatag

### PR DESCRIPTION
**Pull request by beto-aveiga**
**Description:**
Explain the technical implementation of the work done.

**Jira:** (Skip unless you are MA staff)
DP-****

**To Test:**
- [ ] Add steps to test this feature

---

[Peer Review Checklist](https://github.com/massgov/openmass/blob/develop/docs/peer_review_checklist.md)

### CODE REVIEW

**Comment by beto-aveiga** [comment]
@deviantintegral: I just added cacheable dependencies for a few tokens in one file on this PR. Is that expected for:
> Make sure any custom tokens have in mass_* modules are setting appropriate cache tags. I know we’re removing the parent topics and services tokens, but they weren’t setting cache tags at all so we should check other tokens too.

If so, I can add similar code to the other custom modules.

**Comment by weitzman** [comment]
I didn't see anywhere where we "instrument cache hit rate". Is that in the PR yet?

**Comment by beto-aveiga** [comment]
@weitzman not yet. I talked to @alarrimore about this ticket a few days ago but I'm still not sure how to begin, so I just worked on one of the parts in the issue description.

**Comment by weitzman** [comment]
OK. I've move it to Draft

**Pull request closed without merging**
