### PR TITLE
Pass ID to utility nav item that requires it

### PR DESCRIPTION
**Pull request by clairesunstudio**
Log in to utility nav item is missing required id 

Before:
Screen Shot 2024-01-26 at 10 28 39 AM

After:
Screen Shot 2024-01-29 at 12 52 00 PM

### CODE REVIEW

**Comment by joeg8612** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Add a changelog YAML file to this PR</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 43ecb266a1bbd3787734740dcd7baae923f8d5ce
</p>

**Comment by ygannett** [comment]
I see the ID is added, but `aria-controls` is not there as your screenshot shows.
 
Screenshot 2024-02-05 at 9 42 46 AM

**Comment by ygannett** [comment]
`aria-controls` confirmed.
Screenshot 2024-02-05 at 2 24 17 PM

**Review by ygannett — APPROVED** [review]
LGTM.

**Pull request merged**
