### PR TITLE
DP-34221 Add support scripts for database clients.

### PR DESCRIPTION
**Pull request by dstorozhuk**
Add massdbtb and massdbsa scripts for TablePlus and Sequel Ace on macOS.

**Description:**
Added two new DDEV commands to automatically launch the TablePlus and Sequel Ace with mass.gov db connections on macOS. 

**Jira:** 
DP-34221

**To Test:**
TablePlus: 
- [ ] Make sure TablePlus is installed in your system
- [ ] start the project `ddev start`
- [ ] `ddev massdbtb` 
- [ ] Observe that TablePlus is opened automatically and connected to a server/database.

Sequel Ace:
- [ ] Make sure Sequel Ace is installed in your system
- [ ] start the project `ddev start`
- [ ] `ddev massdbsa` 
- [ ] Observe that Sequel Ace is opened automatically and connected to a server/database.

---

[Peer Review Checklist](https://github.com/massgov/openmass/blob/develop/docs/peer_review_checklist.md)

### CODE REVIEW

**Comment by tom-fleming** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Add a changelog YAML file to this PR</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 400f2e744bbd578b7c99769bd910f5073ab00d1e
</p>

**Comment by tom-fleming** [comment]
I tested with TablePlus and looks good to me. Passing to @weitzman to review with Sequel Ace

**Review by tom-fleming — APPROVED** [review]

**Comment by dstorozhuk** [comment]
@tom-fleming  should I just merge by my self?

**Comment by tom-fleming** [comment]
@dstorozhuk Normally, the reviewer merges the PR without adding an approval. I'm also looking for @weitzman to review, so he will merge once he reviews.

**Comment by weitzman** [comment]
The code looks good. IMO it makes sense to simply take over the built in commands `ddev sequelace` and such. Otherwise we have to document these replacement commands and folks have to remember to use them. I think this happens when you simply use same name as the built-in command. If this approach gets difficult, I'm OK with proceeding with custom names.

**Comment by dstorozhuk** [comment]
@weitzman  let me check.

**Comment by dstorozhuk** [comment]
@weitzman yes, it works. Custom local commands just override the global one.

**Pull request merged**
