### PR TITLE
DP-24315 Add Views Porter Stemmer to Collections and Data Listing Views

### PR DESCRIPTION
**Pull request by deviantintegral**
**Description:**

This PR adds https://www.drupal.org/project/views_porter_stemmer and enables it on our views.

Unfortunately, the existing Drupal modules for this functionality require either core's search module or Search API. Instead, this module uses [wamania/php-stemmer](https://github.com/wamania/php-stemmer) which has 800K+ installs and supports multiple languages. I'd like to get a review on the module itself, so feel free to leave comments here and we can fix or open issues upstream as needed.

Who else would like to be added as maintainers to the module?

**Jira:** (Skip unless you are MA staff)
DP-24315

**To Test:**
- [ ] Search for terms with common suffixes such as plurals or "ing" or "ed" in collections and data listings pages.
  * Compare [security policy exceptions](https://www.mass.gov/collections/eotss-service-catalog?topicid=All&title=security+policy+exceptions) on production and [tugboat](https://pr1399-obkqwhqooeqdnohqsuqjgy3uptsvdtes.tugboat.qa/collections/eotss-service-catalog?topicid=All&title=security+policy+exceptions)
  - [ ] In all collections
  - [ ] collections by topic
  - [ ] Data listing
  - [ ] Data listing by topic
- [ ] In the search results, verify that those exact terms do not show up in the title or description to prove stemming is working.

---

[Peer Review Checklist](https://github.com/massgov/openmass/blob/develop/docs/peer_review_checklist.md)

### CODE REVIEW

**Comment by deviantintegral** [comment]
Leaving as draft until I determine if this error occurs on develop or just this branch:

> [Tue Mar 15 14:38:03.312960 2022] [proxy_fcgi:error] [pid 2128] [client 172.19.0.7:36682] AH01071: Got error 'PHP message: [2022-03-15T10:38:03.297575-04:00] php.ERROR: Drupal\\Core\\Database\\InvalidQueryException: Query condition 'taxonomy_term__field_url_name.field_url_name_value IN ()' cannot be empty. in Drupal\\Core\\Database\\Query\\Condition->condition() (line 117 of /var/www/html/docroot/core/lib/Drupal/Core/Database/Query/Condition.php). {"severity_level":3,"exception":"[object] (Drupal\\\\Core\\\\Database\\\\InvalidQueryException(code: 0): Query condition 'taxonomy_term__field_url_name.field_url_name_value IN ()' cannot be empty. at /var/www/html/docroot/core/lib/Drupal/Core/Database/Query/Condition.php:117)"} {"referer":"https://mass.local/admin/structure/views/view/data_listing_topic","ip":"172.19.0.7","request_uri":"https://mass.local/admin/structure/views/view/data_listing_topic/preview/page_topic?_wrapper_format=drupal_ajax","uid":"1","user":"user+1"}PHP message: Uncaught PHP Exception Drupal\\Core\\Database\\InvalidQueryException: "Query condition 'taxonomy_term__field_url_name.field_url_name_value IN ()' cannot be empty." at /var/www/html/docroot/core/lib/Drupal/Core/Database/Query/Condition.php line 117', referer: https://mass.local/admin/structure/views/view/data_listing_topic

**Comment by deviantintegral** [comment]
The above error only occurs when editing views, and does show up on `develop`, so I've filed a new issue for it: https://massgov.atlassian.net/browse/DP-24320

**Review by weitzman — APPROVED** [review]
- Lets add https://www.drupal.org/commonwealth-of-massachusetts as a Sponsoring Organization on the new d.o. project.
- If this changes the autocomplete in a visual way, it would be nice to have a little gif on the project page.

**Comment by weitzman** [comment]
Needs a reroll then is approved for merge. Nice work.

**Comment by deviantintegral** [comment]
> Lets add https://www.drupal.org/commonwealth-of-massachusetts as a Sponsoring Organization

Thank you! I looked earlier and it turns out the autocomplete is "starts with", not "contains":

Screen Shot 2022-03-16 at 1 21 06 PM
 
> If this changes the autocomplete in a visual way, it would be nice to have a little gif on the project page.

Actually, that's a great point. I've never seen the autocomplete in action, even on production pages like https://www.mass.gov/collections/eotss-service-catalog?topicid=All&title=test. Do we know if it was working in the past?

**Review by beto-aveiga — APPROVED** [review]
Looks good to me. Interesting work on the views_porter_stemmer module 👍🏼

**Pull request merged**
