### PR TITLE
DP-24306 Upgrade to the latest Chrome image for tests

### PR DESCRIPTION
**Pull request by deviantintegral**
Replaces #1496.

**Description:**
- Switches to Selenium images so we can easily support ARM. I found no pure up-to-date chromedriver only images.
- Sets up ddev for it.
- Switches one test to prove it works (it passes on my local!)

**Jira:** (Skip unless you are MA staff)
DP-24306

**To Test:**
- [ ] Remove `.ddev/docker-compose.chromedriver.yaml` if it exists
- [ ] Run `ddev service enable selenium-chrome`
- [ ] Run `ddev start`
- [ ] Run `ddev drush -y updatedb && ddev drush -y cim`
- [ ] In your browser, connect to https://mass.local:7900 and log in with VNC using the default password of `secret`.
- [ ] Run `ddev exec vendor/bin/phpunit --testsuite existing-site-javascript`
- [ ] See Chrome start and go through tests.
- [ ] All tests should pass 🎉 

---

[Peer Review Checklist](https://github.com/massgov/openmass/blob/develop/docs/peer_review_checklist.md)

### CODE REVIEW

**Comment by weitzman** [comment]
Code looks great.

Locally, I get 5 test failures. I'm running `phpunit --testsuite existing-site-javascript` and here is the first error 

```
1) Drupal\Tests\mass_alerts\ExistingSiteJavascript\AlertsPlacementTest::testWideAlertPlacement
Behat\Mink\Exception\DriverException: Could not open connection: Could not start a new session. New session request timed out
Build info: version: '4.1.4', revision: '535d840ee2'
System info: host: 'd9a8f9ded4f2', ip: '192.168.96.15', os.name: 'Linux', os.arch: 'aarch64', os.version: '5.10.76-linuxkit', java.version: '11.0.14'
Driver info: driver.version: unknown

/var/www/html/vendor/behat/mink-selenium2-driver/src/Selenium2Driver.php:302
/var/www/html/vendor/behat/mink/src/Session.php:70
/var/www/html/vendor/weitzman/drupal-test-traits/src/GoutteTrait.php:58
/var/www/html/vendor/weitzman/drupal-test-traits/src/ExistingSiteBase.php:53
/var/www/html/vendor/phpunit/phpunit/src/Framework/TestResult.php:726
/var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php:677
/var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php:677
/var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php:677
/var/www/html/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:673
/var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php:143
/var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php:96
```

**Comment by deviantintegral** [comment]
@weitzman I just did a complete reset of my local and followed the above instructions, and tests look to be working. Is it possible you need to do a full `ddev restart` of the web container so it can get the updated environment variables?

Even if tests are failing, you should still see a browser start in VNC. If not, that would confirm that the issue is with connecting to Selenium.

**Comment by weitzman** [comment]
> In your browser, connect to https://mass.local:7900/ and log in with VNC using the default password of secret.

I followed the testing steps in a new instance of openmass and my browser(s) still don't prompt for a secret (its a browser popup?). See screenshot below. It just shows an animation like its waiting to connect. I have verified with `ddev describe` that selenium-chrome service is running.

Also, lets add the instruction above to testing.md. I can't wait to see it in action. 

image

**Comment by deviantintegral** [comment]
@weitzman and I confirmed tests passing on his local today.

On the `noVNC` hang, I found the problem and the solution, but I'm not sure how to make it work with ddev.

The issue is accurately described at https://stackoverflow.com/a/59003635/7982687. I was able to confirm this with a fun workaround. First, I connected using the macOS Screen Sharing client to the selenium container, and loaded chromium manually in a terminal with `chromium --disable-dev-shm-usage`. Then, I loaded http://localhost:7900 several times without errors. However, from the same browser, going to https://mass.local:7900 would throw proxy errors. That confirmed it was some issue caused by adding the nginx proxy.

https://stackoverflow.com/a/46772133/7982687 shows setting `proxy_set_header Connection ""; ` which the ddev config was not, as a workaround for upstream limitations in connection counts. I didn't see any easy way to bump that from noVNC itself. I set that in `/etc/nginx/conf.d/ddev.conf`, restarted with `nginx -s reload`, and everything works!

Except, I can't see how to set that up properly in ddev so it's persistent. I've asked in the ddev discord at https://discord.com/channels/664580571770388500/689166305315520541/976181828341866526

@weitzman we could:

1. Wait a day or two to see if we get a solution for ddev.
2. Remove exposing port 7900, and re-document to use a full VNC client instead, filing a followup ticket to get novnc working.

Thoughts?

**Comment by weitzman** [comment]
Lets wait 1-2 days for Discord discussion.

**Comment by deviantintegral** [comment]
@weitzman I disabled passing noVNC through nginx, which means it's HTTP only for now. Apparently there's some limitations with websockets requiring https, but I can at least connect at a basic level and watch the browser go. If ddev fixes the issue upstream we can re-enable it.

**Comment by weitzman** [comment]
That fixed it. Could we please:

1. Document the DDEV issue thats making us avoid nginx. So we can track upstream fix easily.
2. Document what would need to change when that issue is fixed. That can be done in the composer file as a comment.
3. Can we list selenium-chrome in ddev describe or is that no longer possible?

**Comment by deviantintegral** [comment]
> 1. Document the DDEV issue thats making us avoid nginx. So we can track upstream fix easily.

Randy filed https://github.com/drud/ddev/pull/3861 over the weekend.

> 2. Document what would need to change when that issue is fixed. That can be done in the composer file as a comment.

Added additional details in https://github.com/massgov/openmass/pull/1508/commits/3fc3fc5168ca8997b8ba55038d8f5614e56ccd26.

> 3. Can we list selenium-chrome in ddev describe or is that no longer possible?

Fixed! I had thought that `labels` was only part of the router, but it's needed more broadly.

**Pull request merged**
