### PR TITLE
DP-24668 Upgrade to BackstopJS 6.0.4

### PR DESCRIPTION
**Pull request by deviantintegral**
**Description:**
Upgrades Backstop to the latest version as 4.4.2 is quite out of date.

For locals, if backstop is enabled the service will need to be disabled and re-enabled to pick up the new version.

**Jira:** (Skip unless you are MA staff)
DP-24668

**To Test:**
- [ ] Static review and tests passing.
- [ ] `ddev service enable backstop && ddev restart && ddev exec --service backstop backstop --config=/src/backstop.js test --target=tugboat --list=all --viewport=all` should throw an error message instead of `TypeError: Cannot read property 'replace' of undefined`.
- [ ] A test backstop job against Tugboat should complete (but may throw mismatch errors depending on how you actually run it).

---

[Peer Review Checklist](https://github.com/massgov/openmass/blob/develop/docs/peer_review_checklist.md)

### CODE REVIEW

**Comment by deviantintegral** [comment]
Backstop job running at https://app.circleci.com/pipelines/github/massgov/openmass/18794/workflows/c2831f81-f0ee-410c-87da-f64e26c12dc4

**Comment by deviantintegral** [comment]
The above failed at the very end with an SSL error. I'm rerunning just in case, but if it fails I'm going to wait on investigating until https://github.com/massgov/openmass/pull/1471#issuecomment-1109107147 is resolved.

**Comment by deviantintegral** [comment]
> Error: Evaluation failed: Error: jQuery was not found. This is usually caused by the server returning a 500 response. Please check https://pr1473-wc8p6sejqxuxoczjv8m5iw2mldfpgx3b.tugboat.qa/audit/qag-binderaudit?cachebuster=a1lp0kn in your browser.

I wonder if our tugboat tests aren't waiting for previews to spin up from sleep, as after a few failed tests with this error it started passing.

**Comment by deviantintegral** [comment]
Bumping to 4 concurrent tests saved us ~90s on reference images and ~90s on the target tests. 3 minutes isn't bad, but the resources tab still shows it's basically idle at Circle. While I didn't check at Acquia, Tugboat was also pretty low on load, not even breaking 1.

I'm going to leave it as is for this PR, and open a new PR for testing out different options, since those changes don't actually require a Backstop upgrade.

**Comment by deviantintegral** [comment]
I filed https://massgov.atlassian.net/browse/DP-24805 for the flakey test.

**Comment by tom-fleming** [comment]
Hi @deviantintegral I merged in #1483, and I think the time limit increase from that PR might be causing this conflict. Could you take a look?

**Comment by deviantintegral** [comment]
@tom-fleming resolved via phpstorm's wand 🪄

**Comment by tom-fleming** [comment]
LGTM!

**Pull request merged**
