### PR TITLE
Dp 24022 Disable entity usage and mass_entity_usage modules

### PR DESCRIPTION
**Pull request by beto-aveiga**
**Description:**
Explain the technical implementation of the work done.

**Jira:** (Skip unless you are MA staff)
DP-24022 

**To Test:**
- [ ] Add steps to test this feature

---

[Peer Review Checklist](https://github.com/massgov/openmass/blob/develop/docs/peer_review_checklist.md)

### CODE REVIEW

**Review by weitzman — CHANGES_REQUESTED** [review]
Lets disable mass_entity_usage module as well.

**Comment by beto-aveiga** [comment]
@weitzman I removed the entity_usage_module. Thanks!

**Comment by weitzman** [comment]
We generally do not disable a module and remove its code in same deployment. The reason is that Drupal runs uninstall routines and it cant do so if the code is gone. If you do this you get (minor) error messages due to lack of cleanup. So, I think we need a PR that only uninstalls these 2 modules (i.e. just core.extensions.yml) and then a follow-up to do the rest. Sorry I did not think of this earlier.

**Comment by weitzman** [comment]
Sorry, I mean that this PR can do evrything except for 
1. Dont yet remove entity_usage from composer
2. Dont yet remove mass_entity_usage from the codebase

**Comment by beto-aveiga** [comment]
@weitzman makes total sense. No problem.

**Review by weitzman — APPROVED** [review]

**Pull request merged**
