### PR TITLE
D9 upgrade packages - Analytics/Metadata

### PR DESCRIPTION
**Pull request by weitzman**
**Description:**
This includes a Drush upgrade and this supercedes #448 

**Jira:** (Skip unless you are MA staff)
DP-19463

**To Test:**
- [ ] Review metatags and json-ld page metadata on a few pages. make sure fields are populated.

---

[Peer Review Checklist](https://github.com/massgov/openmass/blob/develop/docs/peer_review_checklist.md)

### CODE REVIEW

**Comment by weitzman** [comment]
@tom-fleming I had  an epiphany regarding the last test failure. Our javascript request all alerts and gets the current Organization from the page metadata. It then filters the list of alerts to show only the Right Org based ones. What may be happening is that this JS is failing to read the Organization and thus not showing the Org alert. Alas I prob can't work on this today.

**Comment by weitzman** [comment]
Well, org alerts are working fine with this PR. All I can think of is we disable the test and merge this PR. Lets open a follow-up to look at the test failure. The test is new and we lived for  a long time without it. Not ideal, but I think its our best option.

To see that Org alerts are working, you can run the script below with `drush scr ./tmp.php` and then view the News node. This script is identical to the code in the test.

```
# tmp.php
<?php

use Drupal\mass_content_moderation\MassModeration;
use Drupal\paragraphs\Entity\Paragraph;

$org_node = \Drupal\node\Entity\Node::create([
  'type' => 'org_page',
  'title' => 'mw',
  'status' => 1,
  'moderation_state' => MassModeration::PUBLISHED,
]);
$org_node->save();

echo 'Org is ' . $org_node->id();

$news_node = \Drupal\node\Entity\Node::create([
  'type' => 'news',
  'title' => 'mw',
  'status' => 1,
  'moderation_state' => MassModeration::PUBLISHED,
  'field_organizations' => ['target_id' => $org_node->id()],
]);
$news_node->save();

echo '. News is ' . $news_node->id();

$alert = \Drupal\node\Entity\Node::create([
  'type' => 'alert',
  'title' => 'mw',
  'field_alert_display' => 'by_organization',
  'moderation_state' => MassModeration::PUBLISHED,
  'status' => 1,
  'field_alert' => Paragraph::create([
    'type' => 'emergency_alert',
    'field_emergency_alert_message' => 'mw',
  ]),
  'field_target_organization' => ['target_id' => $org_node->id()],
]);
$alert->save();

echo '. Alert is ' . $alert->id();
```

**Comment by tom-fleming** [comment]
@weitzman I'm good with that plan. I ran the test as well as checked out some other organization alerts locally, and they look good to me.

**Comment by weitzman** [comment]
Follow up is https://jira.mass.gov/browse/DP-19814

**Pull request merged**
